---
- name: Reboot MikroTik routers
  hosts: mikrotik
  gather_facts: no  # Disable fact gathering
  vars:
    ssh_args: >-
      -o HostKeyAlgorithms=+ssh-dss,ssh-rsa
      -o KexAlgorithms=+diffie-hellman-group14-sha1
      -o StrictHostKeyChecking=no

  tasks:
    - name: Reboot device
      ansible.builtin.command: >
        sshpass -p "{{ ansible_password }}" ssh {{ ssh_args }}
        {{ ansible_user }}@{{ ansible_host }} "/system reboot"
      delegate_to: localhost
      ignore_errors: yes
      register: reboot_result

    - name: Show reboot status
      ansible.builtin.debug:
        var: reboot_result
