---
- name: Reboot MikroTik routers
  hosts: mikrotik
  tasks:
    - name: Reboot device
      ansible.builtin.command: >
        sshpass -p "{{ ansible_password }}" ssh
        -o HostKeyAlgorithms=ssh-dss,ssh-rsa
        -o KexAlgorithms=diffie-hellman-group14-sha1
        -o StrictHostKeyChecking=no
        {{ ansible_user }}@{{ ansible_host }} "/system reboot"
      delegate_to: localhost
      ignore_errors: yes
