---
- name: Reboot MikroTik via API
  hosts: localhost
  vars:
    mikrotik_ip: "192.168.242.20"
    mikrotik_user: "ansible"
    mikrotik_pass: "JVqMuMqGfTSj6dW0"

  tasks:
    - name: Reboot MikroTik
      uri:
        url: "https://{{ mikrotik_ip }}/rest/system/reboot"
        method: POST
        user: "{{ mikrotik_user }}"
        password: "{{ mikrotik_pass }}"
        validate_certs: no  # Only for testing with self-signed certs
        force_basic_auth: yes
      ignore_errors: yes
