---
- name: Reboot MikroTik via raw SSH
  hosts: mikrotik
  tasks:
    - name: Send reboot command
      ansible.builtin.raw: |
        sshpass -p "{{ mikrotik_pass }}" ssh -o StrictHostKeyChecking=no {{ mikrotik_user }}@{{ mikrotik_ip }} "/system reboot"
      ignore_errors: yes
