---
- name: Reboot MikroTik
  hosts: mikrotik
  collections:
    - community.routeros  # Explicitly declare the collection
  tasks:
    - name: Reboot device
      routeros_command:
        commands: "/system reboot"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
      ignore_errors: yes
